title: Madhura
description: "I have a cute li'l bear that codes!"

url: http://objdump.me/
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Madhura Parikh
  twitter: 11011infinity
